### ISSUE TITLE
QQ群无法进入

### ISSUE THREAD

**Issue by huanmeng-qwq** [huzpsb/AIAClient#3]
QQ群加入时提示需要回答问题 但问题是空的 麻烦标注一下答案 @huzpsb

**Comment by huzpsb** [comment]
我手滑了 呃 应该修了

**Comment by huzpsb** [comment]
我手滑了。呃 应该修了


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月23日 00:19:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"John ***@***.***&gt;;
主题: [huzpsb/AIAClient] QQ群无法进入 (Issue #3)




 
QQ群加入时提示需要回答问题 但问题是空的 麻烦标注一下答案 @huzpsb
